driver:
  name: docker
  customize:
    cpus: 4
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[apt-repo]
      - recipe[boilerplate::apt_fast]
      - recipe[php::apt_ondrej_ppa]
  - name: debian-7.4
    run_list:
      - recipe[apt]
      - recipe[apt-repo]
      - recipe[boilerplate::apt_fast]

suites:
  - name: netcommons
    run_list:
      - recipe[chef-dk]
      - recipe[nodejs::nodejs_from_package]
      - recipe[phantomjs]
      - recipe[python]
      - recipe[apache2]
      - recipe[database::mysql]
      - recipe[mysql::server]
      - recipe[jenkins::master]
      - recipe[boilerplate]
      - recipe[mroonga]
      - recipe[boilerplate_php]
      - recipe[netcommons]
    attributes:
      apache:
        version: '2.4'
      apt:
        keyserver_port: 80
      mysql:
        role: 'master'
        server_id: 1
        bind_address: '0.0.0.0'
        server_root_password: 'root'
        server_repl_password: 'repl'
        server_debian_password: ''
      jenkins:
        executor:
          timeout: 600
      boilerplate:
        country: 'jp'
        git:
          use_git_protocol: false
        gitlab: false
        app:
          repo:
            type: 'git'
            uri: 'https://github.com/NetCommons3/NetCommons3.git'
        docs:
          repo:
            type: 'git'
            uri: 'https://github.com/NetCommons3/NetCommons3Docs.git'
