driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: debian-7.5

suites:
  - name: netcommons
    run_list:
      - recipe[chef-dk]
      - recipe[netcommons]
    attributes:
      apache:
        version: '2.4'
      mysql:
        role: 'master'
        server_id: 1
        bind_address: '0.0.0.0'
        server_root_password: 'root'
        server_repl_password: 'repl'
        server_debian_password: ''
      jenkins:
        executor:
          timeout: 600
      boilerplate:
        country: 'jp'
        git:
          use_git_protocol: false
        gitlab: false
        app:
          repo:
            type: 'git'
            uri: 'https://github.com/NetCommons3/NetCommons3.git'
        docs:
          repo:
            type: 'git'
            uri: 'https://github.com/NetCommons3/NetCommons3Docs.git'
