driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: debian-wheezy-7
    driver_config:
      box: debian-wheezy-7
      box_url: https://googledrive.com/host/0B83ZToJ3fGtDVC1DeVVzc3lkc0U/debian-7.5.0-amd64_virtualbox.box

suites:
  - name: netcommons
    run_list:
      - recipe[netcommons]
    attributes:
      boilerplate:
        country: 'jp'
        git:
          use_git_protocol: false
        gitlab: false